defaultSemverRangePrefix: ""

enableTelemetry: false

enableTransparentWorkspaces: false

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferInteractive: true

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.1.1.cjs
